# SONiC to SONiC image update on the running device.
# Command example: 
# ansible-playbook -i inventory --limit SWITCH update.yml --tags update -b -vvvvv -e CMD image_url=URL 

- fail: msg="image_url variable should be provided."
  when: image_url is not defined

- name: Download SONiC image.
  get_url:
    url: "{{ image_url }}"
    dest: /tmp/

- name: Update SONiC image.
  command: sh /tmp/{{ image_url | basename }}
  register: update_output
  ignore_errors: yes

- fail: msg="{{ update_output.stdout }}"
  when:
    - update_output.rc != 0
    - "'Running SONiC has the same version' not in update_output.stdout"

- name: Reboot device.
  command: /sbin/shutdown -r
  async: 0
  poll: 0
  ignore_errors: true

- name: Wait for device to come back.
  local_action: wait_for host={{ ansible_ssh_host }} state=started
