##############################################################################################
### sub-playbook to deploy the docker images needed for the pfcwd test to fanout swtich
################################################################################################

- set_fact:
    fanout_addr: "{{device_info['mgmtip']}}"
    ansible_ssh_user: "{{fanout_root_user}}"
    ansible_ssh_pass: "{{fanout_root_pass}}"

- name: Build containers to save storm arguments and to run storm
  command: make
  args:
    chdir: "{{item}}"
  with_items:
    - roles/test/files/mlnx/docker-tests-pfcgen
    - roles/test/files/mlnx/docker-tests-saveargs
  delegate_to: 127.0.0.1

- name: Copy test match and ignore files to switch
  copy: src="{{ item }}" dest="/var/opt/tms/images/"
  with_items:
    - "roles/test/files/mlnx/docker-tests-pfcgen/pfc_storm.tgz"
    - "roles/test/files/mlnx/docker-tests-saveargs/storm_args.tgz"

- name: Run the command if the specified file does not exist.
  command: mount -o remount, rw /

- name: Update storage driver for Docker
  command: 'sed -i s/\"storage-driver\":\ \"vfs\",/\"storage-driver\":\ \"devicemapper\",\\n\ \ \ \ \"storage-opts\":\ [\\n\ \ \ \ \ \ \ \ \"dm.fs=ext4\"\\n\ \ \ \ ],\/g /opt/tms/bin/docker_config.json'

- name: Remount FS back to ro
  command: mount -r -o remount /

- name: Load and start dockers
  action: apswitch template=mlnx_deploy_pfcwd_fanout.j2
  connection: switch
  args:
    timeout: 600
    login: "{{ switch_login['MLNX-OS'] }}"
