- name: Set specific HWSKU device configs
  set_fact:
    device_configs:
      ACS-MSN2100:
        port_config:
          src: "roles/sonicv2/files/ssw/ACS-MSN2100/port_config.ini"
          dest: "/usr/share/sonic/device/x86_64-mlnx_msn2100-r0/ACS-MSN2100/port_config.ini"
      ACS-MSN2010:
        port_config:
          src: "roles/sonicv2/files/ssw/ACS-MSN2010/port_config_boxer01.ini"
          dest: "/usr/share/sonic/device/x86_64-mlnx_msn2010-r0/ACS-MSN2010/port_config.ini"
        sai_xml:
          src: "roles/sonicv2/files/ssw/ACS-MSN2010/sai_config_boxer01.xml"
          dest: "/usr/share/sonic/device/x86_64-mlnx_msn2010-r0/ACS-MSN2010/sai_2010.xml"
      Mellanox-SN2700-D48C8:
        port_config:
          src: "roles/sonicv2/files/ssw/Mellanox-SN2700-D48C8/port_config.ini"
          dest: "/usr/share/sonic/device/x86_64-mlnx_msn2700-r0/Mellanox-SN2700-D48C8/port_config.ini"
      arc-switch1038:
        port_config:
           src: "roles/sonicv2/files/ssw/ACS-MSN3700/port_config1038.ini"
           dest: "/usr/share/sonic/device/x86_64-mlnx_msn3700-r0/ACS-MSN3700/port_config.ini"
        sai_xml:
           src: "roles/sonicv2/files/ssw/ACS-MSN3700/sai_3700_1038.xml"
           dest: "/usr/share/sonic/device/x86_64-mlnx_msn3700-r0/ACS-MSN3700/sai_3700.xml"
      r-tigris-13:
        port_config:
           src: "roles/sonicv2/files/mlnx/hwsku/r-tigris-13/port_config.ini"
           dest: "/usr/share/sonic/device/x86_64-mlnx_msn3800-r0/ACS-MSN3800/port_config.ini"
      r-tigris-04:
        port_config:
           src: "roles/sonicv2/files/mlnx/hwsku/r-tigris-04/port_config.ini"
           dest: "/usr/share/sonic/device/x86_64-mlnx_msn3800-r0/Mellanox-SN3800-D112C8/port_config.ini"
      r-tigon-04:
        port_config:
           src: "roles/sonicv2/files/mlnx/hwsku/r-tigon-04/port_config.ini"
           dest: "/usr/share/sonic/device/x86_64-mlnx_msn4600c-r0/ACS-MSN4600C/port_config.ini"

- name: Find specific configs if defined for this dut
  set_fact:
    dut_configs: "{{ item.value }}"
  with_dict: "{{ device_configs }}"
  when: item.key == "{{ dut_hwsku }}" or item.key == "{{ dut_hostname }}"

- debug:
    msg: "Deploying next specific configs for {{ dut_hostname }} {{ dut_configs }}"
  when: dut_configs is defined

- name: Deploy specific device configs
  copy:
    src: "{{ item.value.src }}"
    dest: "{{ item.value.dest }}"
  become: true
  with_dict: "{{ dut_configs|default({}) }}"
