root_path: /images/veos-vm
#vm_images_url: https://acsbe.blob.core.windows.net/vmimages
cd_image_filename: Aboot-veos-8.0.0.iso
hdd_image_filename: vEOS-lab-4.16.6M.vmdk
skip_image_downloading: true

vm_console_base: 7000
memory: 2097152
max_fp_num: 4
